#stage1: Git clone and build
FROM maven:3.9.2-eclipse-temurin-17 AS build

WORKDIR /app

RUN git clone https://github.com/subhansmd6/Java-code.git .

RUN mvn clean package -DskipTests

#stage2: Deploy it on tomcat
FROM tomcat:10.1-jdk17

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
